// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRMpVrv1Lf2xwJh4nXm0OfRoSx3tUg67Y',
    appId: '1:81225233235:web:42bc17648ab8baba4767a6',
    messagingSenderId: '81225233235',
    projectId: 'reclaim-1fa7c',
    authDomain: 'reclaim-1fa7c.firebaseapp.com',
    storageBucket: 'reclaim-1fa7c.firebasestorage.app',
    measurementId: 'G-GNCFRP6NR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbALUdqewHor1PD_yv7bEr-9_6Lz-O6NQ',
    appId: '1:81225233235:android:df7a53fe926c061e4767a6',
    messagingSenderId: '81225233235',
    projectId: 'reclaim-1fa7c',
    storageBucket: 'reclaim-1fa7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvzrqhE8wyxiI3EdFYClF7JORg-oQlLpQ',
    appId: '1:81225233235:ios:90e5277d30c7f55c4767a6',
    messagingSenderId: '81225233235',
    projectId: 'reclaim-1fa7c',
    storageBucket: 'reclaim-1fa7c.firebasestorage.app',
    iosClientId: '81225233235-ssla3l0quhcc3ec17p657odq12v6ndre.apps.googleusercontent.com',
    iosBundleId: 'com.example.reclaimFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvzrqhE8wyxiI3EdFYClF7JORg-oQlLpQ',
    appId: '1:81225233235:ios:90e5277d30c7f55c4767a6',
    messagingSenderId: '81225233235',
    projectId: 'reclaim-1fa7c',
    storageBucket: 'reclaim-1fa7c.firebasestorage.app',
    iosClientId: '81225233235-ssla3l0quhcc3ec17p657odq12v6ndre.apps.googleusercontent.com',
    iosBundleId: 'com.example.reclaimFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRMpVrv1Lf2xwJh4nXm0OfRoSx3tUg67Y',
    appId: '1:81225233235:web:1e8fe64ae54cb3ee4767a6',
    messagingSenderId: '81225233235',
    projectId: 'reclaim-1fa7c',
    authDomain: 'reclaim-1fa7c.firebaseapp.com',
    storageBucket: 'reclaim-1fa7c.firebasestorage.app',
    measurementId: 'G-3GXC5PCB22',
  );

}